USE ventas_minoristas;

CREATE TABLE CATEGORIA (
	CATEGORIA_ID INT,
    CATEGORIA_NOMBRE VARCHAR(30),
    PRIMARY KEY(CATEGORIA_ID)
);

-- Prioridad 1.1 --
CREATE TABLE PRODUCTO (
	PRODUCTO_ID INT,
    PRODUCTO_NOMBRE VARCHAR(30),
    PRECIO FLOAT,
    CATEGORIA_ID INT,
    STOCK INT,
    PRIMARY KEY(PRODUCTO_ID),
	FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (CATEGORIA_ID)
);

-- Prioridad 2 --
CREATE TABLE LOCALIDAD (
	LOCALIDAD_ID INT,
    LOCALIDAD_NOMBRE VARCHAR(30),
    PRIMARY KEY(LOCALIDAD_ID)
);

CREATE TABLE PROVINCIA (
	PROVINCIA_ID INT,
    PROVINCIA_NOMBRE VARCHAR(30),
    PRIMARY KEY(PROVINCIA_ID)
);

-- Prioridad 2.1 --
CREATE TABLE UBICACION (
	UBICACION_ID INT,
    LOCALIDAD_ID INT,
    PROVINCIA_ID INT,
    PRIMARY KEY (UBICACION_ID),
    FOREIGN KEY (LOCALIDAD_ID) REFERENCES LOCALIDAD (LOCALIDAD_ID),
    FOREIGN KEY (PROVINCIA_ID) REFERENCES PROVINCIA (PROVINCIA_ID)
);

-- Prioridad 2.2 --
CREATE TABLE SUCURSAL (
	SUCURSAL_ID INT,
    UBICACION_ID INT,
    GERENTE VARCHAR(30),
    PRIMARY KEY(SUCURSAL_ID),
    FOREIGN KEY (UBICACION_ID) REFERENCES UBICACION (UBICACION_ID)
);

CREATE TABLE CLIENTE (
	CLIENTE_ID INT,
    NOMBRE VARCHAR(30),
    SEGMENTO VARCHAR(30),
    UBICACION_ID INT,
    PRIMARY KEY(CLIENTE_ID),
    FOREIGN KEY (UBICACION_ID) REFERENCES UBICACION (UBICACION_ID)
);

/* FALTA DESARROLLAR LA DIMENSION DE TIEMPO

CREATE TABLE DIA_FESTIVO (
	DD_MM_YYYY DATE,categoria
	FESTIVO BOOL,
	PRIMARY KEY (DD_MM_YYYY)
);

CREATE TABLE TRIMESTRE (
	TRIMESTRE INT,
	PRIMARY KEY (MM_NUM)
);

CREATE TABLE ANIO (
	YYYY DATE,
	PRIMARY KEY (YYYY)
);

CREATE TABLE DIA_NOMBRE (
	DD_NOMBRE VARCHAR (10),
	PRIMARY KEY (DD_NOMBRE)
);

CREATE TABLE FECHA (
	DD_MM_YYYY DATE,
	PRIMARY KEY (DD_MM_YYYY)
);

CREATE TABLE HORA (
	HORA INT,
	PRIMARY KEY (HORA)
);
*/


CREATE TABLE VENTAS (
	FACTURA_ID INT,
    SUCURSAL_ID INT,
    CLIENTE_ID INT,
    FECHA DATE,
    HORA TIME,
    PRODUCTO_ID INT,
    CANTIDAD INT,
    MONTO FLOAT,
    PRIMARY KEY(FACTURA_ID),
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL (SUCURSAL_ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (CLIENTE_ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO (PRODUCTO_ID)
);

-- POBLAMOS LA COLUMNA MONTO CON UN CÁLCULO ENTRE LAS TABLAS VENTAS Y PRODUCTO

UPDATE VENTAS
JOIN PRODUCTO ON VENTAS.PRODUCTO_ID = PRODUCTO.PRODUCTO_ID
SET VENTAS.MONTO = VENTAS.CANTIDAD * PRODUCTO.PRECIO;